// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Estilos --',
theme_code_desc : 'Editar c&oacute,digo HTML',
theme_code_title : 'Editor de c&oacute;digo HTML',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Sub índice',
theme_sup_desc : 'Super índice',
theme_hr_desc : 'Insertar linea/regla horizontal',
theme_removeformat_desc : 'Remover formato',
theme_custom1_desc : 'Tu descripci&oacute;n personalizada aqy&iacute;',
insert_image_border : 'Borde',
insert_image_dimensions : 'Dimensiones',
insert_image_vspace : 'espacio vertical',
insert_image_hspace : 'Espacio horizontal',
insert_image_align : 'Alineación',
insert_image_align_default : '-- Not set --',
insert_image_align_baseline : 'Baseline',
insert_image_align_top : 'Arriba',
insert_image_align_middle : 'Medio',
insert_image_align_bottom : 'Abajo',
insert_image_align_texttop : 'TextTop',
insert_image_align_absmiddle : 'Absolute Middle',
insert_image_align_absbottom : 'Absolute Bottom',
insert_image_align_left : 'Izquierda',
insert_image_align_right : 'derecha',
theme_font_size : '-- Tama&ntilde;o fuente --',
theme_fontdefault : '-- Familia de fuentes --',
theme_block : '-- Formato --',
theme_paragraph : 'Párrafo',
theme_div : 'Div',
theme_address : 'Address',
theme_pre : 'Preformateado',
theme_h1 : 'Encabezado 1',
theme_h2 : 'Encabezado 2',
theme_h3 : 'Encabezado 3',
theme_h4 : 'Encabezado 4',
theme_h5 : 'Encabezado 5',
theme_h6 : 'Encabezado 6',
theme_blockquote : 'Cita',
theme_code : 'Código',
theme_samp : 'Code sample',
theme_dt : 'Definition term ',
theme_dd : 'Definition description',
theme_colorpicker_title : 'Seleccionar un color',
theme_colorpicker_apply : 'Aplicar',
theme_forecolor_desc : 'Seleccionar un color de texto',
theme_backcolor_desc : 'Seleccionar un color de fondo',
theme_charmap_title : 'Seleccionar caracter personalizado',
theme_charmap_desc : 'Insertar caracter personalizado',
theme_visualaid_desc : 'Toggle guidelines/invisible elements',
insert_anchor_title : 'Insertar/editar Anclaje con nombre',
insert_anchor_name : 'Anclaje con nombre',
theme_anchor_desc : 'Insertar/editar Anclaje con nombre',
theme_insert_link_titlefield : 'T&iacute;tulo',
theme_clipboard_msg : 'Copiar/cortar/pegar no est&aacute; disponible en Mozilla.\nNecesitas m&aacute;s informaci&oacute sobre este problema?',
theme_path : 'Etiqueta',
cut_desc : 'Cortar',
copy_desc : 'Copiar',
paste_desc : 'Pegar',
link_list : 'Lista de links',
image_list : 'Lista de im&aacute;genes',
browse : 'Browse',
image_props_desc : 'Propiedades de imagen',
newdocument_desc : 'Documento nuevo (limpiar contenido actual)',
class_name : 'Clase',
newdocument : '¿Seguro que quieres limpiar todo el contenido del documento actual?',
about_title : 'A cerca de TinyMCE',
about : 'A cerca',
license : 'Licencia',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Autor',
version : 'Version',
loaded_plugins : 'Plugins cargados',
help : 'Help',
not_set : '-- Not set --',
close : 'Cerrar',
toolbar_focus : 'Saltar a la barra de botones - Alt+Q, Saltar al Editor - Alt-Z, Saltar al elemento de la etiqueta - Alt-X',
invalid_data : 'Error: Los valores de elementos ingresados son incorrectos; estos han sido marcados en rojo.',
more_colors : 'M&aacute;s colores',
color_picker_tab : 'Selector',
color_picker : 'Selector de color',
web_colors_tab : 'Paleta',
web_colors : 'Paleta de colores',
named_colors_tab : 'Nombres',
named_colors : 'Nombres de colores',
color : 'Color:',
color_name : 'Nombre:',
is_email : 'La URL ingresada parece una direcci&oacute;n de email. Quieres agregar el prefijo mailto: requerido?',
is_external : 'La URL ingresada parece un enlace externo.  Quieres agregar el prefijo http:// requerido?'
});
