<?php
if(!defined('DPORTAL')) die();

unset_global_var('BACKUPS_DELETED');
unset_global_var('blog_entry_deleted');
unset_global_var('blog_entry_does_not_exist');
unset_global_var('blog_entry_doesnt_exist');
unset_global_var('blog_entry_error');
unset_global_var('blog_entry_saved');
unset_global_var('blog_post_error');
unset_global_var('blog_post_saved');
unset_global_var('CLEANED');
unset_global_var('comment_empty');
unset_global_var('comment_exceeds');
unset_global_var('content_empty');
unset_global_var('CREATED');
unset_global_var('CREATED_ERROR');
unset_global_var('DELETED');
unset_global_var('DELETED_SECTION');
unset_global_var('DELETE_HOME');
unset_global_var('ERROR');
unset_global_var('FILE_EXISTS');
unset_global_var('GALLERY_CREATED');
unset_global_var('GALLERY_CREATE_ERROR');
unset_global_var('IMAGES_NOT_UPLOADED');
unset_global_var('IMAGES_UPLOADED');
unset_global_var('invalid_email');
unset_global_var('invalid_url');
unset_global_var('loged_ok');
unset_global_var('not_loged_in');
unset_global_var('nick_empty');
unset_global_var('NOT_BACKED_UP');
unset_global_var('PASSWORDS_NO_MATCH');
unset_global_var('RESTORED');
unset_global_var('RESTORE_ERROR');
unset_global_var('SECTION_CREATED');
unset_global_var('SECTION_DELETED');
unset_global_var('SECTION_NOT_DELETED');
unset_global_var('SECTION_NOT_EXIST');
unset_global_var('BACKED_UP');
unset_global_var('TEMPLATE_UPDATED');
unset_global_var('title_empty');
unset_global_var('UPDATED');
unset_global_var('CATEGORY_CREATED');

?>
