// es-CL lang variables

tinyMCE.addToLang('',{
bold_desc : 'Negrita (Ctrl+B)',
italic_desc : 'Cursiva (Ctrl+I)',
underline_desc : 'Subrayado (Ctrl+U)',
striketrough_desc : 'Strikethrough',
justifyleft_desc : 'Alinear a la izquierda',
justifycenter_desc : 'Aliear a la derecha',
justifyright_desc : 'Alinear al centro',
justifyfull_desc : 'Justificado',
bullist_desc : 'Lista sin ordenar',
numlist_desc : 'Lista ordenada',
outdent_desc : 'Outdent',
indent_desc : 'Indent',
undo_desc : 'Deshacer (Ctrl+Z)',
redo_desc : 'Reacer (Ctrl+Y)',
link_desc : 'Insertar/editar enlace',
unlink_desc : 'Desenlazar',
image_desc : 'Insertar/editar imagen',
cleanup_desc : 'Limpiar c&oacute;digo sucio',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : '&quiest;Deseas usar el modo WYSIWYG para esta area de texto?',
insert_link_title : 'Insertar/editar enlace',
insert : 'Insertar',
update : 'Actualizar',
cancel : 'Cancelar',
insert_link_url : 'URL del Link',
insert_link_target : 'Target',
insert_link_target_same : 'Abrir en la misma ventana',
insert_link_target_blank : 'Abrir en una nueva ventana',
insert_image_title : 'Insertar/editar imagen',
insert_image_src : 'URL de la imagen',
insert_image_alt : 'Descripci&oacute;n de la imagen',
help_desc : 'Ayuda',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copiar/cortar/pegar no est&aacute; disponbible en Mozilla ni Firefox.\n&quiest;Deseas m&aacute; informaci&oacute;n sobre este problema?',
popup_blocked : 'Lo siento, pero el Bloqueador de popups ha deshabilitado una ventana que provee funcionalidad a la aplicaci&oacute;n. Deber&aacute;a deshabilitar el bloqueador de popups para este sitio para tener todas las funciones del editor.',
fullscreen_desc : 'Pantalla completa'
});
