<?php

if(!defined('DPORTAL')) die();

unset($_SESSION['BACKUPS_DELETED'],
$_SESSION['blog_entry_deleted'],
$_SESSION['blog_entry_does_not_exist'],
$_SESSION['blog_entry_doesnt_exist'],
$_SESSION['blog_entry_error'],
$_SESSION['blog_entry_saved'],
$_SESSION['blog_post_error'],
$_SESSION['blog_post_saved'],
$_SESSION['CLEANED'],
$_SESSION['comment_empty'],
$_SESSION['comment_exceeds'],
$_SESSION['content_empty'],
$_SESSION['CREATED'],
$_SESSION['CREATED_ERROR'],
$_SESSION['DELETED'],
$_SESSION['DELETED_SECTION'],
$_SESSION['DELETE_HOME'],
$_SESSION['ERROR'],
$_SESSION['FILE_EXISTS'],
$_SESSION['GALLERY_CREATED'],
$_SESSION['GALLERY_CREATE_ERROR'],
$_SESSION['IMAGES_NOT_UPLOADED'],
$_SESSION['IMAGES_UPLOADED'],
$_SESSION['invalid_email'],
$_SESSION['invalid_url'],
$_SESSION['loged_ok'],
$_SESSION['not_loged_in'],
$_SESSION['nick_empty'],
$_SESSION['NOT_BACKED_UP'],
$_SESSION['PASSWORDS_NO_MATCH'],
$_SESSION['RESTORED'],
$_SESSION['RESTORE_ERROR'],
$_SESSION['SECTION_CREATED'],
$_SESSION['SECTION_DELETED'],
$_SESSION['SECTION_NOT_DELETED'],
$_SESSION['SECTION_NOT_EXIST'],
$_SESSION['BACKED_UP'],
$_SESSION['TEMPLATE_UPDATED'],
$_SESSION['title_empty'],
$_SESSION['UPDATED']);

?>
